apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: block-bash
spec:
  kprobes:
  - call: "security_bprm_creds_from_file"
    syscall: false
    args:
    - index: 1
      type: "file"
    selectors:
    - matchArgs:
      - index: 1
        operator: "Equal"
        values:
        - "/bin/bash"
        - "/usr/bin/bash"
      matchActions:
      - action: Sigkill
